// This file is autogenerated by Warp.
// DO NOT EDIT IT MANUALLY.
package config

import (
	"os"
)

// Config is a struct that represents the configuration
type Config struct {
	env string
}

// NewConfig creates a new Config instance
func NewConfig() *Config {
	c := &Config{}

	c.env = os.Getenv("ENV")

	return c
}

// Env returns the ENV value
func (c *Config) Env() string {
	return c.env
}
